"""Add fullname and room number atribute in User

Revision ID: 629a0b985d6a
Revises: 9cd6eac1db72
Create Date: 2025-05-09 18:28:47.394824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '629a0b985d6a'
down_revision: Union[str, None] = '9cd6eac1db72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.String(), nullable=False))
    op.add_column('user', sa.Column('room_number', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'room_number')
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###
