"""Add tables

Revision ID: 4b3de9794215
Revises: 
Create Date: 2025-05-03 20:35:09.733747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from models import RulesType
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b3de9794215'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation_service',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('web', sa.String(), nullable=True),
    sa.Column('contact_mail', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('active_member', sa.Boolean(), nullable=False),
    sa.Column('section_head', sa.Boolean(), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('calendar',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reservation_type', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('max_people', sa.Integer(), nullable=False),
    sa.Column('more_than_max_people_with_permission', sa.Boolean(), nullable=False),
    sa.Column('collision_with_itself', sa.Boolean(), nullable=False),
    sa.Column('collision_with_calendar', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('club_member_rules', RulesType(length=sa.TEXT()), nullable=True),
    sa.Column('active_member_rules', RulesType(length=sa.TEXT()), nullable=False),
    sa.Column('manager_rules', RulesType(length=sa.TEXT()), nullable=False),
    sa.Column('reservation_service_id', sa.UUID(), nullable=False),
    sa.Column('mini_services', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reservation_service_id'], ['reservation_service.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reservation_type')
    )
    op.create_table('mini_service',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('reservation_service_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reservation_service_id'], ['reservation_service.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mini_service')
    op.drop_table('calendar')
    op.drop_table('user')
    op.drop_table('reservation_service')
    # ### end Alembic commands ###
