"""Add attributes in mini service and reservation service

Revision ID: ea3c9c7b12fe
Revises: 629a0b985d6a
Create Date: 2025-05-10 22:56:28.334779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea3c9c7b12fe'
down_revision: Union[str, None] = '629a0b985d6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mini_service', sa.Column('access_group', sa.String(), nullable=True))
    op.add_column('mini_service', sa.Column('room_id', sa.Integer(), nullable=True))
    op.add_column('mini_service', sa.Column('lockers_id', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.create_unique_constraint(None, 'mini_service', ['access_group'])
    op.add_column('reservation_service', sa.Column('access_group', sa.String(), nullable=True))
    op.add_column('reservation_service', sa.Column('room_id', sa.Integer(), nullable=True))
    op.add_column('reservation_service', sa.Column('lockers_id', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.alter_column('reservation_service', 'contact_mail',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservation_service', 'contact_mail',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('reservation_service', 'lockers_id')
    op.drop_column('reservation_service', 'room_id')
    op.drop_column('reservation_service', 'access_group')
    op.drop_constraint('uq_mini_service_access_group', 'mini_service', type_='unique')
    op.drop_column('mini_service', 'lockers_id')
    op.drop_column('mini_service', 'room_id')
    op.drop_column('mini_service', 'access_group')
    # ### end Alembic commands ###
